### ISSUE TITLE
Input fields look odd on small screens

### ISSUE THREAD

**Issue by lverns** [UMM-CSci-3601-S17/lab-3-angular-2-and-spark-lavernetony#7]
I think that a screenshot says it all:
![small_screen](https://cloud.githubusercontent.com/assets/16478445/23097320/98d59298-f5f6-11e6-918c-1e1e501cf4de.png)

**Comment by real-mj-song** [comment]
It's hard to implement a responsive UI without having design prototypes for different screen sizes. So, I'll just try to make it look reasonable if possible.
